version: '3.1'

services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
  redis:
    image: redis:7.4
    restart: always
    ports:
      - "6379:6379"